"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar/Sidebar";
import { usePathname } from "next/navigation";
import SampleRegisterModal from "./components/Modals/SampleRegisterModal";
import useSampleRegisterModal from "./utils/hooks/useSampleRegisterModal";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const sampleRegisterModal = useSampleRegisterModal();

  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <SampleRegisterModal
          isOpen={sampleRegisterModal.isOpen}
          onClose={sampleRegisterModal.onClose}
        />
        {pathname !== "/" && pathname !== "/register" && <Header />}
        <div className="flex flex-row">
          {pathname !== "/" && pathname !== "/register" && <Sidebar />}
          <div
            className={`${
              pathname !== "/" && pathname !== "/register" && "ml-20 md:ml-24 "
            } w-full flex justify-center`}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
